import { Translations, Review } from './types';

export const WEBHOOK_URL = 'https://n8n.queensautoservices.com/webhook-test/5be99bf2-b19b-49f7-82b3-431fb1748b27';

export const translations: Translations = {
    en: {
        readLess: "Read less",
        readMore: "Read more",
        navClaimOffer: "Claim Offer",
        heroClaimOffer: "Claim Brake Offer Now!",
        bookNow: "Book Now",
        limitedSlots: "Professional Brake Service",
        heroTitle: "<span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">Stop Safer Today:</span> $369 Complete Brake <span class=\"text-highlight\">Service</span>",
        heroSubtitle: "Your brakes are your family's last line of defense. Get professional service with premium parts, expert installation, and a 24-month warranty—all for $369. Plus $175 in free safety bonuses to keep you protected on the road.",
        bulletBrakeService: "$369 Premium Brake Service (Pads & Rotors)",
        bulletBonus1: "<strong>Bonus 1:</strong> FREE Tire Rotation ($29 Value)",
        bulletBonus2: "<strong>Bonus 2:</strong> FREE Vehicle Safety Inspection ($79 Value)",
        bulletBonus3: "<strong>Bonus 3:</strong> FREE Brake Fluid Check & Top-Off ($35 Value)",
        bulletBonus4: "<strong>Bonus 4:</strong> 50% OFF Oil Change ($30 Value)",
        heroCTA: "Claim My $369 Brake Package →",
        trustedBy: "<span class=\"text-amber-400\">★★★★★</span> 4.9 from 250+ Elgin drivers",
        scarcityLine: "⏰ Only 3 appointments left this week",
        restrictionsApply: "Restrictions Apply.",
        seeDetails: "See Details",
        disclaimerTitle: "Offer Details",
        disclaimerBody: "Brake special of $369 applies per axle for most cars and light trucks. Offer includes standard brake pads and rotors. Excludes luxury/performance models, heavy-duty trucks, and vehicles requiring specialized or ceramic parts. Cannot be combined with other discounts. Price excludes taxes, shop supplies, and any additional parts or labor required for unforeseen issues (quoted separately). See store for full details.",
        formTitle: "Secure Your Spot - Get Started Here",
        formStep1: "Step 1 of 2 — Your contact details.",
        formStep2: "Step 2 of 2 — Pick your preferred time.",
        formStep3: "", // Unused
        symptomSqueaking: "Brakes are squeaking or grinding",
        symptomSpongy: "Brake pedal feels soft or spongy",
        symptomShaking: "Car shakes when I brake",
        symptomLight: "Brake warning light is on",
        symptomCheck: "Just need a routine brake check",
        nextBtn1: "Next → Lock In My Discount",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        mobileNumber: "Mobile Number",
        vehicleDetails: "Vehicle Details",
        carYear: "Year",
        carMake: "Make",
        carModel: "Model",
        backBtn: "Back",
        nextBtn2: "Next → Pick a Time",
        availableTimes: "Available Times",
        submitBtn: "Secure My Spot →",
        noPaymentRequired: "No payment required — this just saves your spot.",
        requiredField: "This field is required",
        whenToReplaceTitle: "When to Replace Your Brake Pads",
        whenToReplaceSubtitle: "Know the warning signs of worn brake pads to avoid costly repairs and stay safe on the road.",
        watchSignsTitle: "Watch for These Signs",
        signSqueakingTitle: "Squealing or grinding noise",
        signSqueakingBody: "A high-pitched squeal is from a metal scraper on the pad signaling it's time for a replacement.",
        signSpongyTitle: "Soft or spongy pedal",
        signSpongyBody: "If your brake pedal goes further to the floor than usual, it could mean low fluid or worn pads.",
        signStoppingTitle: "Longer stopping distance",
        signStoppingBody: "If you notice your car taking longer to stop, your brakes are losing their effectiveness.",
        signLightTitle: "Dashboard warning light",
        signLightBody: "Most modern vehicles have a sensor that illuminates a light when pads are low.",
        dontWaitTitle: "Don’t Wait—Act Now",
        dontWaitBody: "Delaying replacement risks damaging your expensive rotors and creating a safety hazard.",
        dontWaitCTA: "Book $369 Brake Service →",
        brakesServiced: "100's of Brakes Serviced / Year",
        expertRepairTitle: "Expert Brake Repair, Done with Precision.",
        expertRepairIntro: "At our shop in Elgin, we don’t just fix brakes—we restore confidence. With years of hands-on experience and advanced diagnostics, we ensure your braking system performs safely, reliably, and exactly as it should. Here's what’s included in our process:",
        bulletEquipment: "State-of-the-Art Equipment",
        bulletInspection: "Free Brake Inspection Included",
        bulletWarranty2: "<strong>2-Year / 24,000-Mile Warranty on Brake Repairs</strong>",
        bulletFinancing: "Financing Available Through Snap",
        bulletVehicles: "Valid on Most Vehicles",
        trustedByDrivers: "Trusted by drivers across Elgin, South Elgin, and beyond.",
        feature1Title: "Comprehensive Vehicle Inspection",
        feature1Body: "Before we begin, we conduct a full inspection of your braking system—including rotors, calipers, hoses, and sensors—to identify any underlying issues that could affect performance or safety.",
        feature2Title: "State-of-the-Art Technology",
        feature2Body: "We use high-precision diagnostic tools to evaluate brake pad thickness, rotor condition, and hydraulic function, ensuring accurate repairs that meet factory specifications.",
        feature3Title: "Your Safety is Our Top Priority",
        feature3Body: "At Queens Auto, a brake repair isn't complete without checking the bigger picture. We inspect critical components like ABS sensors and brake lines to ensure your vehicle stops safely and reliably every time.",
        feature4Title: "Final Road Test for Perfection",
        feature4Body: "To finish, we perform a complimentary road test to confirm smooth braking, even pedal feel, and proper response under real-world conditions—so you drive home with confidence.",
        whyImportantTitle: "What Happens When You Ignore That Grinding Noise?",
        whyImportantSubtitle: "Here’s why Elgin drivers fix their brakes before they fail.",
        pain1Title: "Tires & Rotors Wear Faster",
        pain1Body: "Worn or warped rotors cause uneven braking and excessive wear on tires — you could lose $400–$800 in replacements and repairs.",
        pain2Title: "Brakes That Squeal = Less Control",
        pain2Body: "A squealing or grinding noise means your pads are worn — and if you ignore it, you risk losing stopping power in an emergency.",
        pain3Title: "You’ll Pay More Later",
        pain3Body: "Delaying brake service can damage rotors, calipers, and ABS sensors — turning a $200 job into a $1,000+ repair.",
        reliefStatement: "🔒 Backed by the ProVantage Nationwide Warranty — 24 months or 24,000 miles of protection at 30,000+ repair shops across the U.S. and Canada",
        bookServiceCTA2: "Book $369 Brake Service →",
        trustRating: "4.9 Google Rating",
        trustRatingSub: "From 250+ happy customers",
        trustExp: "5,000+ Brake Jobs",
        trustExpSub: "Completed in Elgin since 2007",
        trustWarranty: "2-Year/24K Warranty",
        trustWarrantySub: "Peace of mind guaranteed",
        promiseTitle: "Our Iron-Clad Brake Service Guarantee",
        promiseSubtitle: "We stand behind our work with a promise of quality, transparency, and peace of mind. Every brake service is backed by these four commitments.",
        promise1Title: "Upfront Pricing",
        promise1Body: "The price we quote is the price you pay. No surprises, no hidden fees, and no upselling. Just honest work at a fair price.",
        promise2Title: "Quality Parts",
        promise2Body: "We use only high-quality brake pads and rotors that meet or exceed manufacturer specifications for safety and longevity.",
        promise3Title: "Expert Technicians",
        promise3Body: "Our experienced technicians are brake system specialists, ensuring your service is done right the first time, every time.",
        promise4Title: "24/24 Warranty",
        promise4Body: "Drive with confidence knowing your brake service is covered by our 24-month / 24,000-mile nationwide warranty.",
        testimonialsTitle: "Trusted by <span class=\"text-cyan-400\">Elgin Drivers</span>",
        testimonialsSubtitle: "Elgin drivers count on Queens Auto for fast, affordable, and reliable brake service. See why 25,000+ customers won’t go anywhere else.",
        loadMore: "Load More Reviews",
        aboutTitle: "Elgin’s Trusted Neighborhood Auto Repair Shop",
        aboutBody: "Queens Auto Service is proud to serve the Elgin community with reliable, honest car care. As a family-owned shop, we treat every customer like a neighbor and every vehicle like our own. Whether you're here for brake work, routine maintenance, or unexpected repairs — we’ve got your back with fair prices and real solutions.",
        aboutPoint1: "Honest & Transparent Pricing",
        aboutPoint2: "Experienced, Professional Technicians",
        aboutPoint3: "24-Month / 24,000-Mile Warranty on Most Repairs",
        aboutPoint4: "Over 25,000 cars fixed and counting.",
        aboutSubtext: "For over 17 years, we’ve served Elgin, Carpentersville, Dundee, Algonquin, and nearby communities. We’re a family-owned shop you can trust.",
        parallaxTitle: "Bad Brakes Draining Your Wallet? Get them fixed this week!",
        parallaxBody: "That squealing noise wrecking your peace of mind? At Queens Auto Service, we use industry-leading tech to diagnose and fix the problem with precision. Fill out the form and get back to driving safe, and worry-free.",
        parallaxCTA: "Book $369 Brake Service →",
        serviceAreaTitle: "Proudly Serving Elgin & the Surrounding Communities",
        faqTitle: "Queens Auto Brake Repair FAQ",
        faqSubtitle: "Everything you need to know about our brake services — answered clearly and simply.",
        faq1q: "How do I know if I need new brake pads?",
        faq1a: "If you hear squealing or grinding, your brake pads are down to the metal indicator—which means you have about 1-2 weeks before rotor damage starts. That turns a $369 job into $800+. We'll inspect them free and tell you exactly where you stand—no pressure, just honest answers.",
        faq2q: "How long do brake repairs take?",
        faq2a: "Most brake jobs at Queens Auto are done in under 90 minutes. If we’re replacing rotors or doing anything more in-depth, we’ll let you know and give you a realistic time estimate upfront. You can even book a free inspection today — takes less than a minute.",
        faq3q: "How much does a brake repair cost?",
        faq3a: "Our brake repair service is $369 per axle for most vehicles. Costs may vary slightly depending on parts or vehicle type, but we’ll always give you upfront pricing. And if you need a little flexibility, we also offer financing through Snap Financing. Hit the button below to grab your quote today.",
        faq4q: "Do you offer a warranty on brake repairs?",
        faq4a: "Yes — brake repairs are backed by a 24-month / 24,000-mile warranty. For other mechanical services, the same strong warranty applies. We stand behind every repair we do. Real service, no runaround.",
        faq5q: "Can I drive with worn brakes?",
        faq5a: "Technically yes. Safely? Not really. Worn brakes mean reduced stopping power — and that’s dangerous. The longer you wait, the more damage you risk (to rotors, sensors, even tires). Let’s fix it before it costs more — or worse.",
        faq6q: "What vehicles do you service?",
        faq6a: "We work on most cars, SUVs, and light trucks — foreign or domestic. Not sure if we can help? Just ask. Chances are, we’ve worked on one just like yours. Queens Auto = Local shop, wide expertise.",
        faq7q: "What if I’m not sure it’s my brakes?",
        faq7a: "No problem. Come by for a free check. Whether it’s your pads, rotors, suspension or something else entirely, we’ll diagnose it and walk you through next steps — pressure-free.",
        faq8q: "Do I need to replace all 4 brakes at once?",
        faq8a: "Not always. If the rear brakes are still in good shape, we’ll leave them alone. We only recommend replacing what’s necessary — nothing more, nothing less.",
        faq9q: "Why is my car making a grinding noise when I stop?",
        faq9a: "That usually means your brake pads are completely worn and metal is grinding against your rotors. That can lead to expensive damage fast. Best to get it checked immediately.",
        faqStillQuestions: "Still have questions?",
        faqContactUs: "Call, during business hours to get your questions answered.",
        contactCTA: "Contact Us → (847) 844-1700",
        popupTitle: "Quick Question: When Was the Last Time You Had Your Brakes Checked?",
        popupSubtitle: "Don't wait until it's too late. Check availability in 30 seconds.",
        popupCTA: "Book My $369 Brake Service →",
        privacyPolicy: "Privacy Policy",
        termsOfUse: "Terms of Use",
        callUs: "Call Us:",
        slotsDone: "All appointment times for today have passed."
    },
    es: {
        readLess: "Leer menos",
        readMore: "Leer más",
        navClaimOffer: "Reclamar Oferta",
        heroClaimOffer: "¡Reclamar Oferta de Frenos Ahora!",
        bookNow: "Reservar ahora",
        limitedSlots: "Servicio de Frenos Profesional",
        heroTitle: "<span class=\"text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500\">Frene con Más Seguridad Hoy:</span> Servicio Completo de Frenos por $369",
        heroSubtitle: "Sus frenos son la última línea de defensa de su familia. Obtenga un servicio profesional con piezas de primera calidad, instalación experta y una garantía de 24 meses, todo por $369. Además de $175 en bonos de seguridad gratuitos para mantenerlo protegido en la carretera.",
        bulletBrakeService: "Servicio de Frenos Premium de $369 (Pastillas y Rotores)",
        bulletBonus1: "<strong>Bono 1:</strong> Rotación de Llantas GRATIS (Valor de $29)",
        bulletBonus2: "<strong>Bono 2:</strong> Inspección de Seguridad del Vehículo GRATIS (Valor de $79)",
        bulletBonus3: "<strong>Bono 3:</strong> Revisión y Relleno de Líquido de Frenos GRATIS (Valor de $35)",
        bulletBonus4: "<strong>Bono 4:</strong> 50% DE DESCUENTO en Cambio de Aceite (Valor de $30)",
        heroCTA: "Reclamar mi Paquete de Frenos de $369 →",
        trustedBy: "<span class=\"text-amber-400\">★★★★★</span> 4.9 de más de 250 conductores de Elgin",
        scarcityLine: "⏰ Solo quedan 3 citas esta semana",
        restrictionsApply: "Aplican restricciones.",
        seeDetails: "Ver detalles",
        disclaimerTitle: "Detalles de la oferta",
        disclaimerBody: "El especial de frenos de $369 se aplica por eje para la mayoría de los automóviles y camionetas ligeras. La oferta incluye pastillas y rotores de freno estándar. Excluye modelos de lujo/rendimiento, camiones de servicio pesado y vehículos que requieren piezas especializadas o de cerámica. No se puede combinar con otros descuentos. El precio no incluye impuestos, suministros del taller ni piezas o mano de obra adicionales necesarias para problemas imprevistos (se cotizan por separado). Consulte en la tienda para obtener todos los detalles.",
        formTitle: "Asegura Tu Lugar - Comienza Aquí",
        formStep1: "Paso 1 de 2 — Sus datos de contacto.",
        formStep2: "Paso 2 de 2 — Elija su hora preferida.",
        formStep3: "", // Unused
        symptomSqueaking: "Los frenos rechinan o chirrían",
        symptomSpongy: "El pedal del freno se siente suave o esponjoso",
        symptomShaking: "El coche tiembla cuando freno",
        symptomLight: "La luz de advertencia de los frenos está encendida",
        symptomCheck: "Solo necesito una revisión de frenos de rutina",
        nextBtn1: "Siguiente → Asegurar mi descuento",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo electrónico",
        mobileNumber: "Número de móvil",
        vehicleDetails: "Detalles del vehículo",
        carYear: "Año",
        carMake: "Marca",
        carModel: "Modelo",
        backBtn: "Atrás",
        nextBtn2: "Siguiente → Elegir una hora",
        availableTimes: "Horas disponibles",
        submitBtn: "Asegurar Mi Lugar →",
        noPaymentRequired: "No se requiere pago — esto solo reserva tu lugar.",
        requiredField: "Este campo es obligatorio",
        whenToReplaceTitle: "Cuándo reemplazar las pastillas de freno",
        whenToReplaceSubtitle: "Conozca las señales de advertencia de las pastillas de freno gastadas para evitar reparaciones costosas y mantenerse seguro en la carretera.",
        watchSignsTitle: "Esté atento a estas señales",
        signSqueakingTitle: "Rechinido o chirrido",
        signSqueakingBody: "Un chirrido agudo proviene de un raspador de metal en la pastilla que indica que es hora de reemplazarla.",
        signSpongyTitle: "Pedal suave o esponjoso",
        signSpongyBody: "Si el pedal del freno llega más al fondo de lo habitual, podría significar que hay poco líquido o que las pastillas están gastadas.",
        signStoppingTitle: "Distancia de frenado más larga",
        signStoppingBody: "Si nota que su automóvil tarda más en detenerse, sus frenos están perdiendo su eficacia.",
        signLightTitle: "Luz de advertencia del tablero",
        signLightBody: "La mayoría de los vehículos modernos tienen un sensor que enciende una luz cuando las pastillas están bajas.",
        dontWaitTitle: "No espere, ¡actúe ahora!",
        dontWaitBody: "Retrasar el reemplazo corre el riesgo de dañar sus costosos rotores y crear un peligro para la seguridad.",
        dontWaitCTA: "Reservar servicio de frenos de $369 →",
        brakesServiced: "Cientos de frenos revisados / año",
        expertRepairTitle: "Reparación experta de frenos, hecha con precisión.",
        expertRepairIntro: "En nuestro taller en Elgin, no solo reparamos frenos, restauramos la confianza. Con años de experiencia práctica y diagnósticos avanzados, nos aseguramos de que su sistema de frenado funcione de manera segura, confiable y exactamente como debería. Esto es lo que incluye nuestro proceso:",
        bulletEquipment: "Equipo de última generación",
        bulletInspection: "Inspección de frenos gratuita incluida",
        bulletWarranty2: "<strong>Garantía de 2 años / 24,000 millas en reparaciones de frenos</strong>",
        bulletFinancing: "Financiamiento disponible a través de Snap",
        bulletVehicles: "Válido en la mayoría de los vehículos",
        trustedByDrivers: "Con la confianza de conductores en Elgin, South Elgin y más allá.",
        feature1Title: "Inspección integral del vehículo",
        feature1Body: "Antes de comenzar, realizamos una inspección completa de su sistema de frenado, incluidos rotores, pinzas, mangueras y sensores, para identificar cualquier problema subyacente que pueda afectar el rendimiento o la seguridad.",
        feature2Title: "Tecnología de última generación",
        feature2Body: "Utilizamos herramientas de diagnóstico de alta precisión para evaluar el grosor de las pastillas de freno, el estado de los rotores y la función hidráulica, lo que garantiza reparaciones precisas que cumplen con las especificaciones de fábrica.",
        feature3Title: "Su seguridad es nuestra máxima prioridad",
        feature3Body: "En Queens Auto, una reparación de frenos no está completa sin verificar el panorama general. Inspeccionamos componentes críticos como los sensores de ABS y las líneas de freno para garantizar que su vehículo se detenga de manera segura y confiable en todo momento.",
        feature4Title: "Prueba final en carretera para la perfección",
        feature4Body: "Para terminar, realizamos una prueba de manejo de cortesía para confirmar un frenado suave, una sensación uniforme del pedal y una respuesta adecuada en condiciones del mundo real, para que conduzca a casa con confianza.",
        whyImportantTitle: "¿Qué sucede cuando ignora ese ruido de rechinido?",
        whyImportantSubtitle: "He aquí por qué los conductores de Elgin reparan sus frenos antes de que fallen.",
        pain1Title: "Las llantas y los rotores se desgastan más rápido",
        pain1Body: "Los rotores gastados o deformados provocan un frenado desigual y un desgaste excesivo de las llantas; podría perder entre $ 400 y $ 800 en reemplazos y reparaciones.",
        pain2Title: "Frenos que rechinan = Menos control",
        pain2Body: "Un ruido de rechinido o chirrido significa que las pastillas están gastadas, y si lo ignora, corre el riesgo de perder la potencia de frenado en una emergencia.",
        pain3Title: "Pagará más después",
        pain3Body: "Retrasar el servicio de los frenos puede dañar los rotores, las pinzas y los sensores de ABS, convirtiendo un trabajo de $ 200 en una reparación de más de $ 1,000.",
        reliefStatement: "🔒 Respaldado por la garantía nacional ProVantage: 24 meses o 24,000 millas de protección en más de 30,000 talleres de reparación en los EE. UU. Y Canadá",
        bookServiceCTA2: "Reservar servicio de frenos de $369 →",
        trustRating: "4.9 Calificación de Google",
        trustRatingSub: "De más de 250 clientes satisfechos",
        trustExp: "Más de 5,000 trabajos de frenos",
        trustExpSub: "Completado en Elgin desde 2007",
        trustWarranty: "Garantía de 2 años/24K millas",
        trustWarrantySub: "Tranquilidad garantizada",
        promiseTitle: "Nuestra Garantía de Servicio de Frenos Blindada",
        promiseSubtitle: "Respaldamos nuestro trabajo con una promesa de calidad, transparencia y tranquilidad. Cada servicio de frenos está respaldado por estos cuatro compromisos.",
        promise1Title: "Precios por Adelantado",
        promise1Body: "El precio que cotizamos es el precio que paga. Sin sorpresas, sin cargos ocultos y sin ventas adicionales. Solo trabajo honesto a un precio justo.",
        promise2Title: "Repuestos de Calidad",
        promise2Body: "Utilizamos únicamente pastillas y rotores de freno de alta calidad que cumplen o superan las especificaciones del fabricante para garantizar la seguridad y la longevidad.",
        promise3Title: "Técnicos Expertos",
        promise3Body: "Nuestros técnicos experimentados son especialistas en sistemas de frenos, lo que garantiza que su servicio se realice correctamente la primera vez, siempre.",
        promise4Title: "Garantía 24/24",
        promise4Body: "Conduzca con confianza sabiendo que su servicio de frenos está cubierto por nuestra garantía nacional de 24 meses / 24,000 millas.",
        testimonialsTitle: "Con la confianza de los <span class=\"text-cyan-400\">conductores de Elgin</span>",
        testimonialsSubtitle: "Los conductores de Elgin confían en Queens Auto para un servicio de frenos rápido, asequible y confiable. Vea por qué más de 25,000 clientes no irán a ningún otro lugar.",
        loadMore: "Cargar más reseñas",
        aboutTitle: "El taller de reparación de automóviles de confianza del vecindario de Elgin",
        aboutBody: "Queens Auto Service se enorgullece de servir a la comunidad de Elgin con un cuidado de automóviles confiable y honesto. Como un taller familiar, tratamos a cada cliente como un vecino y a cada vehículo como si fuera nuestro. Ya sea que esté aquí para un trabajo de frenos, mantenimiento de rutina o reparaciones inesperadas, lo respaldamos con precios justos y soluciones reales.",
        aboutPoint1: "Precios honestos y transparentes",
        aboutPoint2: "Técnicos experimentados y profesionales",
        aboutPoint3: "Garantía de 24 meses / 24,000 millas en la mayoría de las reparaciones",
        aboutPoint4: "Más de 25,000 autos reparados y contando.",
        aboutSubtext: "Durante más de 17 años, hemos servido a Elgin, Carpentersville, Dundee, Algonquin y las comunidades cercanas. Somos un taller familiar en el que puede confiar.",
        parallaxTitle: "¿Frenos defectuosos que agotan su billetera? ¡Arréglalos esta semana!",
        parallaxBody: "¿Ese ruido de rechinido que arruina tu tranquilidad? En Queens Auto Service, utilizamos tecnología líder en la industria para diagnosticar y solucionar el problema con precisión. Complete el formulario y vuelva a conducir de forma segura y sin preocupaciones.",
        parallaxCTA: "Reservar servicio de frenos de $369 →",
        serviceAreaTitle: "Orgullosamente sirviendo a Elgin y las comunidades circundantes",
        faqTitle: "Preguntas frecuentes sobre la reparación de frenos de Queens Auto",
        faqSubtitle: "Todo lo que necesita saber sobre nuestros servicios de frenos, respondido de forma clara y sencilla.",
        faq1q: "¿Cómo sé si necesito pastillas de freno nuevas?",
        faq1a: "Si escucha un rechinido o un chirrido, sus pastillas de freno están hasta el indicador de metal, lo que significa que tiene aproximadamente 1-2 semanas antes de que comience el daño en el rotor. Eso convierte un trabajo de $369 en más de $800. Los inspeccionaremos de forma gratuita y le diremos exactamente cuál es su situación, sin presiones, solo respuestas honestas.",
        faq2q: "¿Cuánto tiempo tardan las reparaciones de frenos?",
        faq2a: "La mayoría de los trabajos de frenos en Queens Auto se realizan en menos de 90 minutos. Si estamos reemplazando rotores o haciendo algo más a fondo, se lo haremos saber y le daremos una estimación de tiempo realista por adelantado. Incluso puede reservar una inspección gratuita hoy, toma menos de un minuto.",
        faq3q: "¿Cuánto cuesta una reparación de frenos?",
        faq3a: "Nuestro servicio de reparación de frenos cuesta $369 por eje para la mayoría de los vehículos. Los costos pueden variar ligeramente según las piezas o el tipo de vehículo, pero siempre le daremos un precio por adelantado. Y si necesita un poco de flexibilidad, también ofrecemos financiamiento a través de Snap Financing. Presione el botón de abajo para obtener su cotización hoy.",
        faq4q: "¿Ofrecen garantía en las reparaciones de frenos?",
        faq4a: "Sí, las reparaciones de frenos están respaldadas por una garantía de 24 meses / 24,000 millas. Para otros servicios mecánicos, se aplica la misma garantía sólida. Respaldamos cada reparación que hacemos. Servicio real, sin rodeos.",
        faq5q: "¿Puedo conducir con los frenos gastados?",
        faq5a: "Técnicamente sí. ¿De forma segura? No realmente. Los frenos gastados significan una menor potencia de frenado, y eso es peligroso. Cuanto más espere, más daño corre el riesgo (a los rotores, sensores e incluso a los neumáticos). Arreglémoslo antes de que cueste más, o peor.",
        faq6q: "¿Qué vehículos revisan?",
        faq6a: "Trabajamos en la mayoría de los automóviles, SUV y camionetas ligeras, ya sean extranjeros o nacionales. ¿No está seguro si podemos ayudarlo? Solo pregunte. Lo más probable es que hayamos trabajado en uno como el suyo. Queens Auto = Taller local, amplia experiencia.",
        faq7q: "¿Qué pasa si no estoy seguro de que sean mis frenos?",
        faq7a: "No hay problema. Venga para una revisión gratuita. Ya sean sus pastillas, rotores, suspensión o algo completamente diferente, lo diagnosticaremos y lo guiaremos a través de los siguientes pasos, sin presiones.",
        faq8q: "¿Necesito reemplazar los 4 frenos a la vez?",
        faq8a: "No siempre. Si los frenos traseros todavía están en buen estado, los dejaremos en paz. Solo recomendamos reemplazar lo que es necesario, ni más ni menos.",
        faq9q: "¿Por qué mi coche hace un ruido de rechinido cuando me detengo?",
        faq9a: "Eso generalmente significa que las pastillas de freno están completamente gastadas y el metal está rozando contra los rotores. Eso puede provocar daños costosos rápidamente. Es mejor que lo revisen de inmediato.",
        faqStillQuestions: "¿Aún tienes preguntas?",
        faqContactUs: "Llame durante el horario comercial para que le respondan sus preguntas.",
        contactCTA: "Contáctenos → (847) 844-1700",
        popupTitle: "Pregunta rápida: ¿Cuándo fue la última vez que revisó sus frenos?",
        popupSubtitle: "No espere hasta que sea demasiado tarde. Verifique la disponibilidad en 30 segundos.",
        popupCTA: "Reservar mi servicio de frenos de $369 →",
        privacyPolicy: "Política de privacidad",
        termsOfUse: "Términos de Uso",
        callUs: "Llámanos:",
        slotsDone: "Todas las citas para hoy han pasado."
    }
};

export const allReviews: Review[] = [
    { "name": "Mark Devino", "text": "I got fast, friendly service here for a flat repair. Without any kind of appointment I got the tire fixed while I waited maybe 25 minutes. The repair was inexpensive. Great shop I will definitely be back." },
    { "name": "Bashar Danial", "text": "Gino and the Team, Wow!!! I recently had the misfortune of breaking down on the side of the road with a bad tire, called Queens Auto Service and spoke with Gino. They were very receptive and responsive, we got the vehicle to their shop, they immediately jumped into action and replaced the bad tire with a new tire and had us back on the road, all of this in under one hour!!! I highly recommend Queens Auto Service and Gino and the Team at this shop, top-notch!! Thank you for the help and great service." },
    { "name": "A C", "text": "HIGHLY RECOMMEND QUEENS TIRE IN ELGIN. Friendliness customer service. Prices are affordable, no extra unnecessary add ons. This will be my ONLY go to place. Much more than just tires" },
    { "name": "Nursultan Abeuov", "text": "Good place to get your tire, balancing, Alignment and more. Always good quality. Ill do all my pickup trucks alignment here, never regret it. Nick Abeuov🇰🇿" },
    { "name": "Kristin Kastern", "text": "Tires and axle shaft. They were amazing. I am new to the area and I am very happy 😊 with my service. They were honest and were able to fit me in on holiday weekend. The pricing was great. They even gave me really good advice about the car and tires. I am going to them in the future with all my cars. Thank you so much." },
    { "name": "Tim Chapman", "text": "Great customer service, went in for a second opinion for tire patch, nail in tire and advised not repairable too close to outer wall of tire. Good price and wound up buying all 4 new tires speedy service, Marco was a pleasure doing business with you. Would recommend this shop to anyone. These guys get it done and professional." },
    { "name": "Lavira Johnson", "text": "I called at the last minute to get in and have my battery replaced. I was given an exact quote, the part was in stock and I was encouraged to come in right away. When I arrived, I was greeted and checked in immediately in a very kind and professional manner by Baltazar. I was quoted 30-45 mins and it didn't feel like more than 25 and I came in about an hour before closing time. Fast and exceptional service, reasonably priced.. Will definitely patronize this business again. Pep Boys, only 5 minutes away wanted almost $300 more for the same service and wanted to-keep my car overnight." },
    { "name": "Theresa Hoge", "text": "Highly recommend! Probably one of the best shops I’ve been too. Service is professional and super nice. I had to get my brakes done. They got me in the same day, were done in a few hours and explained everything to me. I also needed to get new tires and they walked me through all the options. I recently ran over a nail and they were able to patch the hole right away. Quality of work is great and the customer service is everything! Really appreciate them!" }
];

export const allReviewsEs: Review[] = [
    { "name": "Mark Devino", "text": "Recibí un servicio rápido y amigable aquí para una reparación de pinchazo. Sin ningún tipo de cita, me arreglaron el neumático mientras esperaba unos 25 minutos. La reparación no fue cara. Gran taller, definitivamente volveré." },
    { "name": "Bashar Danial", "text": "¡Gino y el equipo, guau! Recientemente tuve la mala suerte de quedarme tirado en la carretera con un neumático en mal estado, llamé a Queens Auto Service y hablé con Gino. Fueron muy receptivos y respondieron rápidamente, llevamos el vehículo a su taller, inmediatamente se pusieron en acción y reemplazaron el neumático dañado por uno nuevo y nos pusieron de nuevo en la carretera, ¡todo esto en menos de una hora! Recomiendo encarecidamente Queens Auto Service y a Gino y el equipo de este taller, ¡de primera categoría! Gracias por la ayuda y el gran servicio." },
    { "name": "A C", "text": "RECOMIENDO ENCARECIDAMENTE QUEENS TIRE EN ELGIN. Amabilidad en el servicio al cliente. Los precios son asequibles, sin extras innecesarios. Este será mi ÚNICO lugar de referencia. Mucho más que solo neumáticos." },
    { "name": "Nursultan Abeuov", "text": "Buen lugar para comprar neumáticos, balanceo, alineación y más. Siempre de buena calidad. Haré la alineación de todas mis camionetas aquí, nunca me arrepiento. Nick Abeuov🇰🇿" },
    { "name": "Kristin Kastern", "text": "Neumáticos y eje. Fueron increíbles. Soy nueva en la zona y estoy muy contenta 😊 con mi servicio. Fueron honestos y pudieron atenderme en un fin de semana festivo. El precio fue excelente. Incluso me dieron muy buenos consejos sobre el coche y los neumáticos. En el futuro, iré a ellos con todos mis coches. Muchas gracias." },
    { "name": "Tim Chapman", "text": "Excelente servicio al cliente, fui para una segunda opinión sobre un parche de neumático, un clavo en el neumático y me informaron que no era reparable por estar demasiado cerca de la pared exterior del neumático. Buen precio y terminé comprando los 4 neumáticos nuevos, servicio rápido. Marco, fue un placer hacer negocios contigo. Recomendaría este taller a cualquiera. Estos chicos hacen el trabajo y son profesionales." },
    { "name": "Lavira Johnson", "text": "Llamé en el último momento para que me reemplazaran la batería. Me dieron un presupuesto exacto, la pieza estaba en stock y me animaron a ir de inmediato. Cuando llegué, me saludaron y me registraron de inmediato de una manera muy amable y profesional por Baltazar. Me dijeron que tardarían entre 30 y 45 minutos y no parecieron más de 25, y llegué aproximadamente una hora antes de la hora de cierre. Servicio rápido y excepcional, a un precio razonable. Definitivamente volveré a este negocio. Pep Boys, a solo 5 minutos de distancia, quería casi $300 más por el mismo servicio y querían quedarse con mi coche durante la noche." },
    { "name": "Theresa Hoge", "text": "¡Lo recomiendo encarecidamente! Probablemente uno de los mejores talleres en los que he estado. El servicio es profesional y súper agradable. Tuve que hacer mis frenos. Me atendieron el mismo día, terminaron en unas pocas horas y me explicaron todo. También necesitaba neumáticos nuevos y me guiaron a través de todas las opciones. Recientemente pisé un clavo y pudieron parchar el agujero de inmediato. ¡La calidad del trabajo es excelente y el servicio al cliente lo es todo! ¡Realmente los aprecio!" }
];
